name: reviewdog
on: [pull_request]
jobs:
  misspell:
    name: runner / codespell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: codespell
        uses: plettich/action-codespell@master
        with:
          reporter: github-pr-review
          level: info

